#!/bin/sh
filename=desc.po
dir=$1
filename=`basename $filename`

cd $1

echo "Generate desc.po"

rm -f desc.po; touch desc.po

cat > desc.po  <<EOF
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: fcitx-dev@googlegroups.com\n"
"POT-Creation-Date: 2010-11-17 11:48+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
EOF


cd ..
find data -iname "*.desc" | while read f
do
    awk '/^[\t ]*Description=/ { print "\n#: '$f':" NR"\n" "msgid \"" substr($0, 13)"\"\n" "msgstr \"\""}' $f >> $dir/$filename
done

grep -Hn '^\[' data/*.desc | awk ' "^[" { split($0, a, ":"); split(a[3], b, "/"); print "\n#: "a[1]":"a[2]"\nmsgid \""substr(b[2], 1, length(b[2])-1)"\"\nmsgstr \"\"" }' >> $dir/$filename

grep -Hn '^\[' data/*.desc | awk ' "^[" { split($0, a, ":"); split(a[3], b, "/"); print substr(b[1], 2); }'  | sort | uniq | awk '{ print "\n# unknown\nmsgid \""$0"\"\nmsgstr \"\""; }' >> $dir/$filename

grep -h 'Enum[0-9]' data/*.desc | sed -e 's/Enum[0-9]=//g' | sort | uniq | awk '{ print "\n#: unknown\nmsgid \""$0"\"\nmsgstr \"\""; }' >> $dir/$filename

